### PR TITLE
Fix braced initalization and binary zero optimizations

### PR DESCRIPTION
**Pull request by JamesLee-Jones**
Previously, when mutating expressions such as `char test {24}`, the braced initialization expression `{24}` would also get mutated (as noted in #225). This lead to compilation errors. This is resolved by avoiding the mutation of `InitListExpr`.

Also, the optimization checks for the case when both arguments to a binary expression were zero was previously wrong (as noted in #222). This is resolved.

Fixes: #222, #225.

### CODE REVIEW

**Comment by JamesLee-Jones** [comment]
This appears to only be failing because of the CI as noted in #227.

**Review by afd — APPROVED** [review]
